"""Update farmer schema

Revision ID: 1d3db663e31e
Revises: a8ed661f3c82
Create Date: 2025-01-25 00:34:34.448081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d3db663e31e'
down_revision: Union[str, None] = 'a8ed661f3c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_farmers_id', table_name='farmers')
    op.drop_index('ix_farmers_location', table_name='farmers')
    op.drop_index('ix_farmers_name', table_name='farmers')
    op.drop_index('ix_farmers_phone', table_name='farmers')
    op.drop_index('ix_farmers_soil_type', table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('crops', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('soil_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='farmers_pkey')
    )
    op.create_index('ix_farmers_soil_type', 'farmers', ['soil_type'], unique=False)
    op.create_index('ix_farmers_phone', 'farmers', ['phone'], unique=False)
    op.create_index('ix_farmers_name', 'farmers', ['name'], unique=False)
    op.create_index('ix_farmers_location', 'farmers', ['location'], unique=False)
    op.create_index('ix_farmers_id', 'farmers', ['id'], unique=False)
    # ### end Alembic commands ###
