"""Update farmer schema

Revision ID: ffe17ecd2fdf
Revises: 
Create Date: 2025-01-24 16:28:13.007087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffe17ecd2fdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_farmers_id', table_name='farmers')
    op.drop_index('ix_farmers_location', table_name='farmers')
    op.drop_index('ix_farmers_name', table_name='farmers')
    op.drop_index('ix_farmers_phone', table_name='farmers')
    op.drop_index('ix_farmers_soil_type', table_name='farmers')
    op.drop_table('farmers')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('crops', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('soil_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='farmers_pkey')
    )
    op.create_index('ix_farmers_soil_type', 'farmers', ['soil_type'], unique=False)
    op.create_index('ix_farmers_phone', 'farmers', ['phone'], unique=False)
    op.create_index('ix_farmers_name', 'farmers', ['name'], unique=False)
    op.create_index('ix_farmers_location', 'farmers', ['location'], unique=False)
    op.create_index('ix_farmers_id', 'farmers', ['id'], unique=False)
    # ### end Alembic commands ###
